local mod = "SUPER"
local launch = "uwsm app -- "

hl.bind(mod .. " + Return", hl.dsp.exec_cmd(launch .. "kitty"))
hl.bind(mod .. " + E", hl.dsp.exec_cmd(launch .. "thunar"))
hl.bind(mod .. " + D", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call launcher toggle"))
hl.bind(mod .. " + B", hl.dsp.exec_cmd(launch .. "firefox"))
hl.bind(mod .. " + W", hl.dsp.window.close())
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = 1 }))
hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen())
hl.bind(mod .. " + P", hl.dsp.window.pseudo())
hl.bind(mod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mod .. " + L", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call lock lock"))
hl.bind(mod .. " + CTRL + L", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call lock lock"))
hl.bind(mod .. " + SHIFT + E", hl.dsp.exec_cmd("wlogout"))
hl.bind(mod .. " + ALT + Return", hl.dsp.exec_cmd(launch .. "kitty -e tmux new"))
hl.bind(mod .. " + SHIFT + Return", hl.dsp.exec_cmd(launch .. "firefox"))
hl.bind(mod .. " + Space", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call launcher toggle"))
hl.bind(mod .. " + CTRL + Space", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call wallpaper toggle"))
hl.bind(mod .. " + ALT + Space", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call island toggle"))
hl.bind(mod .. " + code:61", hl.dsp.exec_cmd("~/.local/bin/friend-scale-cycle"))
hl.bind(mod .. " + ALT + code:61", hl.dsp.exec_cmd("~/.local/bin/friend-scale-cycle --reverse"))
hl.bind(mod .. " + S", hl.dsp.workspace.toggle_special("scratchpad"))
hl.bind(mod .. " + ALT + S", hl.dsp.window.move({ workspace = "special:scratchpad" }))
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CTRL + Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind("ALT + Tab", hl.dsp.window.cycle_next())
hl.bind("ALT + Tab", hl.dsp.window.bring_to_top())

hl.bind(mod .. " + Left", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + Right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + Up", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + Down", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + Down", hl.dsp.window.move({ direction = "d" }))

for i = 1, 10 do
    local key = i % 10
    hl.bind(mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"))
hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | satty --filename -"))
hl.bind(mod .. " + F10", hl.dsp.exec_cmd("q-shot --pick"))
hl.bind(mod .. " + F11", hl.dsp.exec_cmd("q-shot region"))
hl.bind(mod .. " + F12", hl.dsp.exec_cmd("q-shot full"))
hl.bind(mod .. " + CTRL + V", hl.dsp.exec_cmd("cliphist list | fuzzel --dmenu --prompt='Clipboard: ' | cliphist decode | wl-copy"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call island brightness +5"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call island brightness -5"), { locked = true, repeating = true })
hl.bind("ALT + XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call island brightness +1"), { locked = true, repeating = true })
hl.bind("ALT + XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.local/bin/friend-shell ipc call island brightness -1"), { locked = true, repeating = true })
hl.bind("SHIFT + XF86MonBrightnessUp", hl.dsp.exec_cmd("q-kbd-brightness up"), { locked = true, repeating = true })
hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd("q-kbd-brightness down"), { locked = true, repeating = true })
hl.bind("XF86KbdBrightnessUp", hl.dsp.exec_cmd("q-kbd-brightness up"), { locked = true, repeating = true })
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("q-kbd-brightness down"), { locked = true, repeating = true })
hl.bind("XF86KbdLightOnOff", hl.dsp.exec_cmd("q-kbd-brightness cycle"), { locked = true })
