background = "#120c15"
foreground = "#eee7f0"
cursor = "#eee7f0"
selection_background = "#392541"
selection_foreground = "#f8f2f9"
accent = "#b68dcc"
surface = "#1d1421"
surface_alt = "#2b1d31"
border = "#493351"
muted = "#98879d"
subtext = "#c0b1c4"
success = "#81b996"
warning = "#d0ab74"
error = "#dc7c86"
color0 = "#1d1421"
color1 = "#dc7c86"
color2 = "#81b996"
color3 = "#d0ab74"
color4 = "#829fce"
color5 = "#b68dcc"
color6 = "#79afb7"
color7 = "#c0b1c4"
color8 = "#5c4562"
color9 = "#e6969e"
color10 = "#9ac9aa"
color11 = "#dec08e"
color12 = "#9db3da"
color13 = "#c8a8d8"
color14 = "#92c1c7"
color15 = "#f8f2f9"
