font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0

foreground #bebebe
background #121212
selection_foreground #bebebe
selection_background #515151
cursor #eaeaea
cursor_text_color #121212
url_color #f59e0b
active_border_color #e68e0d
inactive_border_color #595959
active_tab_foreground #121212
active_tab_background #e68e0d
inactive_tab_foreground #bebebe
inactive_tab_background #333333
color0 #333333
color1 #d35f5f
color2 #ffc107
color3 #b91c1c
color4 #e68e0d
color5 #d35f5f
color6 #bebebe
color7 #bebebe
color8 #8a8a8d
color9 #b91c1c
color10 #ffc107
color11 #b90a0a
color12 #f59e0b
color13 #b91c1c
color14 #eaeaea
color15 #ffffff

window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no
cursor_shape block
allow_remote_control yes

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+q close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab -1

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
